model:
  latent_dim: 32
  latent_patch_size: 1
  text_vocab_size: 50000
  text_tokenizer_repo: zuhri025/lm_weights_scratch
  text_tokenizer_subfolder: checkpoint-24000
  model_dim: 768
  num_layers: 16
  num_heads: 12
  mlp_ratio: 2.875
  text_mlp_ratio: 4.5
  speaker_mlp_ratio: 2.6
  text_dim: 512
  text_layers: 17
  text_heads: 4
  speaker_dim: 384
  speaker_layers: 6
  speaker_heads: 6
  speaker_patch_size: 1
  timestep_embed_dim: 256
  adaln_rank: 192

train:
  hf_dataset: zuhri025/munch-1-latent-NEW-parquet
  hf_text_col: text
  hf_latent_col: latent
  hf_speaker_col: speaker_id
  hf_filter_max_frames: 712
  hf_repo_id: zuhri025/irodori-tts-checkpoints
  hf_resume_repo: zuhri025/irodori-tts-checkpoints
  tensorboard_enabled: true
  tensorboard_dir: runs/train_500m
  batch_size: 8
  gradient_accumulation_steps: 4
  num_workers: 16
  dataloader_persistent_workers: true
  dataloader_prefetch_factor: 4
  allow_tf32: true
  compile_model: false
  precision: bf16
  optimizer: muon
  muon_momentum: 0.95
  learning_rate: 0.0001
  weight_decay: 0.01
  lr_scheduler: wsd
  warmup_steps: 1000
  stable_steps: 44000
  min_lr_scale: 0.01
  max_steps: 50000
  max_text_len: 2048
  text_condition_dropout: 0.1
  speaker_condition_dropout: 0.1
  timestep_stratified: true
  max_latent_steps: 750
  fixed_target_latent_steps: 750
  fixed_target_full_mask: true
  log_every: 10
  save_every: 1000
  wandb_enabled: false
  wandb_project:
  wandb_entity:
  wandb_run_name:
  wandb_mode: online
  ddp_find_unused_parameters: false
  valid_ratio: 0.0005
  valid_every: 1000
  seed: 0
